apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudkitchen
spec:
  selector:
    matchLabels:
      app: cloudkitchen
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudkitchen
    spec:
      containers:
        - name: cloudkitchen
          image: ghcr.io/sabeeshvk/cloudkitchen:main              
          ports:
            - containerPort: 8080
