apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudkitchen
spec:
  selector:
    matchLabels:
      app: cloudkitchen
  replicas: 4
  template:
    metadata:
      labels:
        app: cloudkitchen
    spec:
      containers:
        - name: cloudkitchen
          image: ghcr.io/sabeeshvk/cloudkitchen:main              
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 1000Mi  
            limits:
              cpu: 300m
              memory: 2000Mi